# Generated by Django 3.2.13 on 2023-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastUpdate',
            field=models.DateTimeField(null=True),
        ),
    ]
