# Generated by Django 3.2.13 on 2023-03-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='problemCnt',
            field=models.IntegerField(default=0),
        ),
    ]
