# Generated by Django 3.2.13 on 2023-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_standing_problemcnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='score1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='standing',
            name='score2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='standing',
            name='score3',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='standing',
            name='score4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='standing',
            name='score5',
            field=models.IntegerField(default=-1),
        ),
    ]
